/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => GroupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/groups' | '/login' | '/settings' | '/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/groups' | '/login' | '/settings' | '/groups/$groupId'
  id: '__root__' | '/' | '/groups' | '/login' | '/settings' | '/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof GroupsRoute
    }
  }
}

interface GroupsRouteChildren {
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsGroupIdRoute: GroupsGroupIdRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsRoute: GroupsRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
